name: Github iqiyi

on:
    push:
        branches:
            - main
    schedule:
        - cron: '5 0 * * *'
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout codes
              uses: actions/checkout@v2
            - name: 'Set up Python'
              uses: actions/setup-python@v1
              with:
                python-version: 3.7
            - name: "运行 WPS自动邀请"
              run: python3 test.py
              env:
                WPS_KEY: ${{ secrets.WPS_KEY }}
            - name: Commit files
              run: |
                git config --local user.email "action@github.com"
                git config --local user.name "GitHub Action"
                git add .
                git commit -m "$(date +%Y%m%d%H%M%S)" -a
            - name: 'Push changes'
              uses: ad-m/github-push-action@master
              with:
                github_token: ${{ secrets.TOKEN }}
